

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_exchange
    username: root
    password: bvnsrs2000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

debug: true

server:
  port: 7979

